Repository CS2113-AY1819S2-T09-3/main, pull requests merged in 2019-03, with the labels that each got.

#37 [v1.2] As a user I can view the previous version of my task
  src/main/java/seedu/project/logic/commands/CompareCommand.java
  src/main/java/seedu/project/logic/commands/EditCommand.java
  src/main/java/seedu/project/logic/parser/AddCommandParser.java
  src/main/java/seedu/project/logic/parser/CompareCommandParser.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/main/java/seedu/project/model/Model.java
  src/main/java/seedu/project/model/ModelManager.java
  src/main/java/seedu/project/model/project/Project.java
  src/main/java/seedu/project/model/project/ReadOnlyProject.java
  src/main/java/seedu/project/model/project/VersionedProject.java
  src/main/java/seedu/project/model/task/Task.java
  src/main/java/seedu/project/model/task/UniqueTaskList.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
  src/test/java/seedu/project/model/ProjectTest.java
  src/test/java/seedu/project/storage/JsonAdaptedTaskTest.java
Labels: priority.High, status.ToReview

#75 [v1.2] Update Developer Guide with implementation of import/export enhancement
  docs/DeveloperGuide.adoc
Labels: status.ToMerge

#76 [v1.2] Add shorthand aliases to the rest of the commands
  docs/UserGuide.adoc
  src/main/java/seedu/project/logic/commands/ClearCommand.java
  src/main/java/seedu/project/logic/commands/FindCommand.java
  src/main/java/seedu/project/logic/commands/HistoryCommand.java
  src/main/java/seedu/project/logic/commands/ListCommand.java
  src/main/java/seedu/project/logic/commands/RedoCommand.java
  src/main/java/seedu/project/logic/commands/SelectCommand.java
  src/main/java/seedu/project/logic/commands/UndoCommand.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/test/java/seedu/project/logic/parser/ProjectParserTest.java
Labels: component.Logic, priority.Medium, status.ToMerge, type.Enhancement

#80 Update Developer Guide with implementation of list tag feature implementation
  docs/DeveloperGuide.adoc
Labels: priority.High, status.ToReview

#82 [v1.2] Update developer guide with implementation of command aliases and calendar
  docs/DeveloperGuide.adoc
Labels: priority.High

#81 Update developer guide with implementation of Compare Task Feature
  docs/DeveloperGuide.adoc
Labels: priority.High, status.ToReview

#84 update user guide structure
  docs/UserGuide.adoc
Labels: status.ToMerge

#88 Update User Guide, Section 5.2.7, 6.2.10, 7, 8, Appendix
  docs/UserGuide.adoc
Labels: priority.High, status.ToReview

#87 Update User Guide, Section 5 - 5.2.6
  docs/UserGuide.adoc
Labels: priority.High, status.ToReview

#86 Update User Guide, Section 6.2.5 - 6.2.10
  docs/UserGuide.adoc
Labels: priority.High, status.ToMerge

#90 Update User Guide, Section 6.1 - 6.2.4
  docs/UserGuide.adoc
Labels: priority.High, status.ToReview

#93 Update User Guide, Section 1 - 4
  docs/UserGuide.adoc
  docs/images/applayout.png
  docs/images/apporg.png
Labels: priority.High, status.ToReview

#95 [v1.3] Add List Command for Project and Task
  src/main/java/seedu/project/logic/commands/ListCommand.java
  src/main/java/seedu/project/logic/commands/ListProjectCommand.java
Labels: priority.High, status.ToMerge

#98 [v1.3] Fix interaction between Project and Task and bugs at export feature
  src/main/java/seedu/project/logic/LogicManager.java
  src/main/java/seedu/project/logic/commands/ExportCommand.java
  src/main/java/seedu/project/logic/commands/ListProjectCommand.java
  src/main/java/seedu/project/logic/parser/ExportCommandParser.java
  src/main/java/seedu/project/ui/MainWindow.java
Labels: status.ToReview

#73 view task history: able to view pass commands made on a specific task
  docs/DeveloperGuide.adoc
  src/main/java/seedu/project/logic/CommandHistory.java
  src/main/java/seedu/project/logic/LogicManager.java
  src/main/java/seedu/project/logic/commands/AddCommand.java
  src/main/java/seedu/project/logic/commands/CompareCommand.java
  src/main/java/seedu/project/logic/commands/DeleteCommand.java
  src/main/java/seedu/project/logic/commands/EditCommand.java
  src/main/java/seedu/project/logic/commands/SelectCommand.java
  src/main/java/seedu/project/logic/commands/TaskHistoryCommand.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/main/java/seedu/project/logic/parser/TaskHistoryCommandParser.java
  src/main/java/seedu/project/model/Model.java
  src/main/java/seedu/project/model/ModelManager.java
  src/main/java/seedu/project/model/project/VersionedProject.java
  src/main/resources/view/CommandBox2.fxml
  src/test/java/systemtests/ProjectSystemTest.java
Labels: component.Logic, component.Model, priority.Medium, status.ToReview, type.Epic

#102 [v1.3] Add CompletedCommand as part of analyse feature
  docs/UserGuide.adoc
  src/main/java/seedu/project/logic/commands/CompletedCommand.java
  src/main/java/seedu/project/logic/parser/CompletedCommandParser.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
Labels: component.Logic, priority.Medium, type.Epic

#79 [v1.2] List all tags and its relevant tasks
  docs/UserGuide.adoc
  src/main/java/seedu/project/logic/commands/ListTagCommand.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/main/java/seedu/project/model/tag/Tag.java
Labels: component.Logic, priority.Medium, status.ToReview, type.Story

#105 Reposense unable to identify authors despite populated commit history
  .gitignore
  _response/config.json
Labels: priority.High, status.ToReview, type.Bug, type.Task

#112 [v1.3] Add completed tag when CompletedCommand is called
  src/main/java/seedu/project/logic/commands/CompletedCommand.java
  src/main/java/seedu/project/logic/commands/EditCommand.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/main/java/seedu/project/model/task/Task.java
Labels: component.Logic, type.Epic

#107 [v1.3] Fix Test Cases
  src/main/java/seedu/project/logic/commands/ClearCommand.java
  src/main/java/seedu/project/logic/commands/CompletedCommand.java
  src/main/java/seedu/project/logic/parser/CompletedCommandParser.java
  src/main/java/seedu/project/model/Name.java
  src/main/java/seedu/project/model/project/Project.java
  src/main/java/seedu/project/model/project/VersionedProject.java
  src/main/java/seedu/project/model/task/UniqueTaskList.java
  src/main/java/seedu/project/ui/MainWindow.java
  src/main/java/seedu/project/ui/StatusBarFooter.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/project/TestApp.java
  src/test/java/seedu/project/logic/LogicManagerTest.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
  src/test/java/seedu/project/logic/commands/ClearCommandTest.java
  src/test/java/seedu/project/logic/commands/CommandTestUtil.java
  src/test/java/seedu/project/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/project/logic/commands/EditCommandTest.java
  src/test/java/seedu/project/logic/commands/FindCommandTest.java
  src/test/java/seedu/project/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/project/logic/commands/ListCommandTest.java
  src/test/java/seedu/project/logic/commands/RedoCommandTest.java
  src/test/java/seedu/project/logic/commands/SelectCommandTest.java
  src/test/java/seedu/project/logic/commands/UndoCommandTest.java
  src/test/java/seedu/project/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/project/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/project/logic/parser/ParserUtilTest.java
  src/test/java/seedu/project/logic/parser/ProjectParserTest.java
  src/test/java/seedu/project/model/ProjectTest.java
  src/test/java/seedu/project/model/VersionedProjectTest.java
  src/test/java/seedu/project/model/task/NameTest.java
  src/test/java/seedu/project/model/task/TaskTest.java
  src/test/java/seedu/project/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/project/storage/JsonProjectStorageTest.java
  src/test/java/seedu/project/storage/JsonSerializableProjectTest.java
  src/test/java/seedu/project/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/project/storage/StorageManagerTest.java
  src/test/java/seedu/project/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/project/testutil/TaskBuilder.java
  src/test/java/seedu/project/testutil/TypicalTasks.java
  src/test/java/seedu/project/ui/BrowserPanelTest.java
  src/test/java/seedu/project/ui/TaskListPanelTest.java
  src/test/java/seedu/project/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ProjectSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: priority.Medium, status.Ongoing, type.Bug

#111 [v1.3] Add group tag feature
  src/main/java/seedu/project/logic/commands/DefineTagCommand.java
  src/main/java/seedu/project/logic/parser/CliSyntax.java
  src/main/java/seedu/project/logic/parser/DefineTagCommandParser.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/main/java/seedu/project/model/Model.java
  src/main/java/seedu/project/model/ModelManager.java
  src/main/java/seedu/project/model/ProjectList.java
  src/main/java/seedu/project/model/project/UniqueGroupTagList.java
  src/main/java/seedu/project/model/project/exceptions/DuplicateGroupTagException.java
  src/main/java/seedu/project/model/project/exceptions/GroupTagNotFoundException.java
  src/main/java/seedu/project/model/tag/GroupTag.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
  src/test/java/seedu/project/ui/CommandBoxTest.java
Labels: component.Logic, component.Model, priority.High, status.ToReview

#101 [v1.3] Update Developer Guide
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/diagrams/ViewTaskHistorySequenceDiagram.pptx
  docs/images/DeleteTaskSdForLogic.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SDforDeletePerson.png
  docs/images/SDforDeleteTask.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/images/ViewTaskHistorySeq1.png
  docs/images/ViewTaskHistorySeq2.png
  docs/images/compare 3.png
  docs/images/compare1.png
  docs/images/compare2.png
Labels: priority.Medium, status.Ongoing

#116 [v1.4] Add group tag to task feature
  src/main/java/seedu/project/logic/commands/AddTagCommand.java
  src/main/java/seedu/project/logic/commands/DefineTagCommand.java
  src/main/java/seedu/project/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/main/java/seedu/project/model/ProjectList.java
  src/main/java/seedu/project/model/ReadOnlyProjectList.java
Labels: component.Logic, component.Model, priority.High, status.ToReview

#117 [v1.3] Update Developer Guide with updated import/export implementation
  docs/DeveloperGuide.adoc
Labels: status.ToReview, type.Task
