Repository CS2113-AY1819S2-T09-3/main, pull requests merged in 2019-04, with the labels that each got.

#119 [v1.3] developer guide: fixed typo and update diagrams
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/images/DeleteTaskSdForLogic.png
  docs/images/UiClassDiagram.png
Labels: status.ToReview

#122 [v1.3] Update User Guide with import/export and command summary
  docs/UserGuide.adoc
Labels: type.Task

#124 [v1.3] fix bug for compare command
  docs/AboutUs.adoc
  src/main/java/seedu/project/model/project/VersionedProject.java
Labels: component.Model, severity.Low, status.ToReview, type.Bug

#121 Update User Guide
  docs/UserGuide.adoc
Labels: priority.Medium

#127 [v1.3] Bug when importing project and panel shading
  src/main/java/seedu/project/logic/commands/ImportCommand.java
  src/main/java/seedu/project/ui/MainWindow.java
Labels: status.ToReview, type.Bug

#128 [v1.3] fixed bug for group tag
  src/main/java/seedu/project/logic/commands/AddTagCommand.java
Labels: type.Bug

#129 [v1.3] Fix display of completed tag
  src/main/java/seedu/project/logic/commands/CompletedCommand.java
Labels: component.Logic, type.Bug

#123 [v1.3] update readme.adoc
  README.adoc
  docs/AboutUs.adoc
  docs/images/Ui.png
Labels: status.ToReview

#131 [v1.3] fix listDeadline bug
  src/main/java/seedu/project/logic/commands/ListByDeadlineCommand.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/main/java/seedu/project/model/task/Task.java
Labels: priority.High, severity.High, type.Bug

#134 [v1.4] Update Project Portfolio Page for Mock Submission - josephinetanadi
  docs/DeveloperGuide.adoc
  docs/team/josephinetanadi.adoc
Labels: type.Task

#135 [v1.4] Update Project Portfolio Page for Mock Submission - andreathniah
  _reposense/config.json
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/andreathniah.adoc
Labels: status.ToReview

#142 [v1.4] Add AnalyseCommand for statistics
  docs/team/rachellim10.adoc
  src/main/java/seedu/project/commons/core/Messages.java
  src/main/java/seedu/project/logic/commands/AnalyseCommand.java
  src/main/java/seedu/project/logic/commands/CompletedCommand.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
Labels: component.Logic, type.Epic

#145 [v1.4] Update AnalyseCommand to show percentage completed
  src/main/java/seedu/project/logic/commands/AnalyseCommand.java
Labels: component.Logic, type.Epic

#144 [v1.4] Update test for import, export and storage
  src/main/java/seedu/project/logic/commands/AddCommand.java
  src/main/java/seedu/project/logic/commands/DeleteCommand.java
  src/main/java/seedu/project/logic/commands/ExportCommand.java
  src/main/java/seedu/project/logic/commands/ImportCommand.java
  src/main/java/seedu/project/model/project/NameContainsKeywordsPredicate.java
  src/main/java/seedu/project/storage/JsonSerializableProject.java
  src/test/data/JsonProjectListStorageTest/notJsonFormatProject.json
  src/test/data/JsonProjectStorageTest/invalidAndValidTask.json
  src/test/data/JsonProjectStorageTest/invalidTask.json
  src/test/data/JsonSerializableProjectListTest/duplicateProject.json
  src/test/data/JsonSerializableProjectListTest/duplicateTask.json
  src/test/data/JsonSerializableProjectListTest/emptyProject.json
  src/test/data/JsonSerializableProjectListTest/invalidTask.json
  src/test/data/JsonSerializableProjectListTest/typicalProject.json
  src/test/data/JsonSerializableProjectTest/duplicateTask.json
  src/test/data/JsonSerializableProjectTest/invalidTask.json
  src/test/data/JsonSerializableProjectTest/typicalTasks.json
  src/test/java/guitests/guihandles/ProjectListPanelHandle.java
  src/test/java/seedu/project/logic/LogicManagerTest.java
  src/test/java/seedu/project/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
  src/test/java/seedu/project/logic/commands/CommandTestUtil.java
  src/test/java/seedu/project/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/project/logic/commands/ExportCommandTest.java
  src/test/java/seedu/project/logic/commands/ImportCommandTest.java
  src/test/java/seedu/project/storage/JsonAdaptedProjectTest.java
  src/test/java/seedu/project/storage/JsonProjectListStorageTest.java
  src/test/java/seedu/project/storage/JsonProjectStorageTest.java
  src/test/java/seedu/project/storage/JsonSerializableProjectListTest.java
  src/test/java/seedu/project/storage/JsonSerializableProjectTest.java
  src/test/java/seedu/project/testutil/TypicalTasks.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: status.Ongoing

#148 [v1.4] Update date and month format
  src/main/java/seedu/project/logic/commands/AddCommand.java
  src/main/java/seedu/project/model/util/SampleDataUtil.java
  src/test/data/JsonProjectStorageTest/invalidAndValidTask.json
  src/test/data/JsonProjectStorageTest/invalidTask.json
  src/test/data/JsonSerializableProjectListTest/duplicateProject.json
  src/test/data/JsonSerializableProjectListTest/duplicateTask.json
  src/test/data/JsonSerializableProjectListTest/invalidTask.json
  src/test/data/JsonSerializableProjectListTest/typicalProject.json
  src/test/data/JsonSerializableProjectTest/duplicateTask.json
  src/test/data/JsonSerializableProjectTest/typicalTasks.json
  src/test/java/seedu/project/logic/commands/CommandTestUtil.java
  src/test/java/seedu/project/logic/parser/ParserUtilTest.java
  src/test/java/seedu/project/model/task/DeadlineTest.java
  src/test/java/seedu/project/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/project/testutil/TaskBuilder.java
  src/test/java/seedu/project/testutil/TypicalTasks.java
  src/test/java/seedu/project/ui/TaskListPanelTest.java
Labels: type.Task

#147 [v1.4] Fix Bugs
  src/main/java/seedu/project/logic/commands/CompareCommand.java
  src/main/java/seedu/project/logic/commands/RedoCommand.java
  src/main/java/seedu/project/logic/commands/TaskHistoryCommand.java
  src/main/java/seedu/project/logic/commands/UndoCommand.java
  src/main/java/seedu/project/model/task/Deadline.java
Labels: severity.Medium, status.ToReview, type.Bug

#140 [v1.4] Update test for compare and taskhistory
  src/main/java/seedu/project/logic/CommandHistory.java
  src/main/java/seedu/project/logic/commands/TaskHistoryCommand.java
  src/main/java/seedu/project/model/project/VersionedProject.java
  src/test/java/seedu/project/logic/commands/CompareCommandTest.java
  src/test/java/seedu/project/logic/commands/TaskHistoryCommandTest.java
  src/test/java/seedu/project/testutil/TaskBuilder.java
Labels: priority.Medium

#146 [v1.4] Fix bugs in AddTagCommand and DefineTagCommand
  docs/UserGuide.adoc
  src/main/java/seedu/project/logic/commands/AddTagCommand.java
  src/main/java/seedu/project/logic/commands/DefineTagCommand.java
  src/main/java/seedu/project/logic/commands/ListTagCommand.java
  src/main/java/seedu/project/logic/parser/ProjectParser.java
  src/main/java/seedu/project/model/Model.java
  src/main/java/seedu/project/model/ModelManager.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
Labels: status.Completed, status.ToReview, type.Bug

#172 [v1.4] Update PPP and relevant sections of UG/DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AfterImportCommand.png
  docs/images/BeforeImportCommand.png
  docs/images/applayoutclean.png
  docs/team/josephinetanadi.adoc
Labels: type.Task

#137 [v1.4] update PPP for mock submission - YRJ
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/arhjaye.adoc
Labels: status.ToReview, type.Task

#174 [v1.4] Update Browser Panel to Display task
  src/main/java/seedu/project/logic/commands/SelectCommand.java
  src/main/java/seedu/project/model/task/Task.java
  src/main/java/seedu/project/ui/BrowserPanel.java
  src/main/java/seedu/project/ui/MainWindow.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/WebViewUtil.java
  src/test/java/seedu/project/ui/BrowserPanelTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ProjectSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: component.UI, type.Bug

#175 Fix Bugs
  src/main/java/seedu/project/model/task/Deadline.java
Labels: priority.Medium, status.ToReview, type.Bug

#179 [v1.4] Bug for selecting project and adding task and selecting task
  src/main/java/seedu/project/logic/commands/SelectCommand.java
  src/main/java/seedu/project/ui/MainWindow.java
Labels: type.Bug

#180 Fix 'percentage displayed' bug in AnalyseCommand
  src/main/java/seedu/project/logic/commands/AnalyseCommand.java
Labels: component.Logic, type.Bug

#182 Update UML Diagram (Compare & Task History)
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/CompareCommandSequenceDiagram.pptx
  docs/diagrams/TaskHistoryCommandSeq.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/images/compare2.png
  docs/images/comparesample.PNG
  docs/images/compareseq.png
  docs/images/taskhistorysample.png
  docs/images/taskhistoryseq.png
  docs/team/arhjaye.adoc
Labels: status.ToReview

#183 Fix Bug & Test cases
  src/main/java/seedu/project/logic/commands/AddCommand.java
  src/main/java/seedu/project/logic/commands/AddTagCommand.java
  src/main/java/seedu/project/model/ModelManager.java
  src/main/java/seedu/project/model/ProjectList.java
  src/main/java/seedu/project/model/project/VersionedProject.java
  src/main/java/seedu/project/model/task/Task.java
  src/main/java/seedu/project/model/task/UniqueTaskList.java
  src/test/java/seedu/project/logic/LogicManagerTest.java
  src/test/java/seedu/project/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
  src/test/java/seedu/project/logic/commands/CompareCommandTest.java
Labels: severity.High, status.ToReview, type.Bug

#184 [v1.4] Fix single project related bugs
  src/main/java/seedu/project/logic/commands/AddCommand.java
  src/main/java/seedu/project/logic/commands/AddTagCommand.java
  src/main/java/seedu/project/logic/commands/CompletedCommand.java
  src/main/java/seedu/project/logic/commands/DeleteCommand.java
  src/main/java/seedu/project/logic/commands/EditCommand.java
  src/main/java/seedu/project/logic/commands/ListProjectCommand.java
  src/main/java/seedu/project/logic/commands/SortByDeadlineCommand.java
  src/test/java/seedu/project/logic/commands/CompareCommandTest.java
  src/test/java/seedu/project/logic/commands/TaskHistoryCommandTest.java
Labels: type.Bug

#185 [v1.4] fix sort and compare
  src/main/java/seedu/project/logic/commands/AddCommand.java
  src/main/java/seedu/project/logic/commands/CompareCommand.java
  src/main/java/seedu/project/logic/commands/SortByDeadlineCommand.java
  src/main/java/seedu/project/model/project/VersionedProject.java
  src/test/java/seedu/project/logic/commands/CompareCommandTest.java
Labels: severity.High, type.Bug

#187 [v1.4] Update import and export system test
  src/main/java/seedu/project/logic/commands/UndoCommand.java
  src/main/java/seedu/project/model/Model.java
  src/main/java/seedu/project/model/ModelManager.java
  src/main/java/seedu/project/model/project/UniqueProjectList.java
  src/main/java/seedu/project/model/util/SampleDataUtil.java
  src/main/java/seedu/project/ui/MainWindow.java
  src/main/java/seedu/project/ui/TaskListPanel.java
  src/test/java/seedu/project/TestApp.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
  src/test/java/seedu/project/logic/commands/CommandTestUtil.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ExportCommandSystemTest.java
  src/test/java/systemtests/ImportCommandSystemTest.java
  src/test/java/systemtests/ProjectSystemTest.java
Labels: type.Task

#191 [v1.4] Add test cases for CompletedCommand and AnalyseCommand
  src/main/java/seedu/project/logic/commands/CompletedCommand.java
  src/test/java/seedu/project/logic/commands/AnalyseCommandTest.java
  src/test/java/seedu/project/logic/commands/CompletedCommandTest.java
Labels: type.Task

#189 [v1.4] Add test codes for DefineTag, AddTag and ListTag
  docs/UserGuide.adoc
  src/main/java/seedu/project/logic/commands/AddTagCommand.java
  src/main/java/seedu/project/logic/commands/DefineTagCommand.java
  src/main/java/seedu/project/logic/commands/ListTagCommand.java
  src/main/java/seedu/project/model/Model.java
  src/main/java/seedu/project/model/ModelManager.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
  src/test/java/seedu/project/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/project/logic/commands/CommandTestUtil.java
  src/test/java/seedu/project/logic/commands/DefineTagCommandTest.java
  src/test/java/seedu/project/logic/commands/ListTagCommandTest.java
Labels: priority.High, status.ToReview, type.Task

#194 [v1.4] Update Project Portfolio for Final Submission - josephinetanadi
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AfterExportCommand.png
  docs/images/ExportUML.png
  docs/images/ImportUML.png
  docs/team/josephinetanadi.adoc
Labels: type.Task

#195 [v1.4] Update UG, DG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Analyse.png
  docs/images/AnalyseOutcome.PNG
  docs/images/CmdAlias.png
  docs/images/Completed.png
  docs/images/CompletedOutcome.PNG
  docs/images/DemoLayout.png
  docs/team/rachellim10.adoc
Labels: type.Task

#196 [v1.4] Update Project Portfolio for Final Submission - josephinetanadi
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/josephinetanadi.adoc
Labels: type.Task

#197 [v1.4] Update UG, DG and PPP for Final Submission - andreathniah
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddTagCommandSeq.pptx
  docs/diagrams/DefineTagCommandSeq.pptx
  docs/diagrams/ListTagCommandSeq.pptx
  docs/images/AddTagSequenceDiagram.png
  docs/images/AfterAddTag.png
  docs/images/AfterDefineTag.png
  docs/images/AfterListTag.png
  docs/images/DefineTagSequenceDiagram.png
  docs/images/ListTagSequenceDiagram.png
  docs/team/andreathniah.adoc
  docs/team/josephinetanadi.adoc
  src/main/java/seedu/project/logic/commands/AddTagCommand.java
  src/main/java/seedu/project/logic/commands/DefineTagCommand.java
  src/main/java/seedu/project/logic/commands/ListTagCommand.java
  src/main/java/seedu/project/model/Model.java
  src/main/java/seedu/project/model/ModelManager.java
  src/test/java/seedu/project/logic/commands/AddCommandTest.java
  src/test/java/seedu/project/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/project/logic/commands/DefineTagCommandTest.java
  src/test/java/seedu/project/logic/commands/ListTagCommandTest.java
Labels: priority.High, type.Task

#199 [v1.4] Update minor changes to UG, DG and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/rachellim10.adoc
Labels: type.Task

#200 [v1.4] Update Project Portfolio for Final Submission - josephinetanadi
  docs/team/josephinetanadi.adoc
Labels: type.Task

#212 [v1.4] Add minor changes to PPP
  docs/team/rachellim10.adoc
Labels: type.Task

#211 [v1.4] Update PPP
  docs/team/josephinetanadi.adoc
Labels: type.Task
